CommandHeader command
string product_id
uint64 fifo_sequence
uint8 station_id
uint8 conveyor_id
int64 target_step
---
bool success
string product_id
uint8 station_id
string position_command_id
int64 estimated_step
int64 position_error_steps
uint8 position_source
uint16 error_code
string reason
---
string stage
int64 estimated_step
